FORMAT: 1A
HOST: http://190.216.254.173:3090/businesscore/api/v1

# xcouty-businessCore

Lista de servicios Back-End API

## Usuario Login/Registro [/user/login]
### Login [POST]

+ Request (application/json)
+ Attributes
    + email: `montilla.t31@gmail.com` (required) - Email de usuario
    + password: `12345678` (required) - Contraseña de usuario
    + lenguage: `EN` (enum, optional) - Lenguaje utilizado desde el celular
        + EN
        + ES
        
+ Response 200 (application/json)

    + Body

            {
               "id":1,
               "name":"oscar",
               "last_name":"Montilla",
               "email":"montilla.t31@gmail.com",
               "image_profile":"http://35.227.223.87/image120181010154016319.jpg",
               "access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTU0Mjc3NTkxNywic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.isK6QGCjLFudqXA0NHNyPgWNMwGq5MDgjlwwMOx5WRqwQ6Ba3gVj5PEzem_2CpHXCG8Rqlfr6tijeSVyvEd0ww"
            }
            
+ Response 400 (application/json)         

  El usuario no existe en el systema

  + Body

            {
               "error_code": "M0001",
               "message": "The email (:email) is not registered in the system"
            }
            
+ Response 400 (application/json)         

  La contraseña suministrada es invalida 
  + Body

            {
               "error_code": "M0002",
               "message": "The password provided is invalid"
            }


### Registro [POST /user/register]

+ Request (application/json)
+ Attributes
    + name: `Oscar`  (required) - Nombre de usuario
    + las_name: `Montilla` (required) - Apellido de usuario
    + email: `montilla.t31@gmail.com` (required) - Email de usuario
    + password: `12345678` (required) - Contraseña de usuario
    + password_repeated: `12345678` (required) - Campo para repetir contraseña
    + lenguage: `EN` (enum, required) -  Lenguaje utilizado desde el celular
        + EN
        + ES
 
+ Response 201 (application/json)
  
            {
                "id": 1,
                "name": "Oscar",
                "last_name": "Montilla",
                "email": "montilla.t31@gmail.com",
                "image_url": "http://35.227.223.87/image120181010154016319.jpg"
            }

+ Response 400 (application/json)         

    El email ya se encuentra registrado en el systema

  + Body

  {"error_code": "M0004","message": "The email (:email) is already registered in our system"}
    
+ Response 400 (application/json)     

  El campo de password no coincide con el campo password_repeated

  + Body

  {"error_code": "M0006","fields": [{"code": "M0006","field": "password","issue": "The two passwords supplied do not match"},{"code": "M0006","field": "password_repeated","issue": "The two passwords supplied do not match"}]}

### Login/Registro Facebook [POST /user/login/facebook]

+ Request (application/json)
+ Attributes
    + token: `dsahjdqwfcghauasidwqdiuchsaui;dwqqw` (required) - Token suministrado por la API de facebook
    + email: `montilla.t31@gmail.com` (required) - Email suministrado por la API de facebook
    + lenguage: EN (enum, optional)
        + EN
        + ES
 
+ Response 200 (application/json)   
  Login de usuario

   + Body
            {
               "id":1,
               "name":"Eduardo",
               "last_name":"Gonzales",
               "email":"montilla.t31@gmail.com",
               "image_url": "http://35.227.223.87/image120181010154016319.jpg"
            }
            
+ Response 201 (application/json)
  Registro de usuario
  
   + Body
            {
               "id":1,
               "name":"Eduardo",
               "last_name":"Gonzales",
               "email":"montilla.t31@gmail.com",
               "image_profile":"URL"
            }


+ Response 400 (application/json)         
  El token suministrado no es valido

  + Body
  {"error_code": "M0008","message": "The supplied token is not valid"}

## Ajustes de usuario [/user/{userId}/setting]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario 

### Obtener parametros de ajuste de usuario[GET]

+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  + Body
     {
        "language_code": "EN",
        "language_name": "ENGLISH",
        "weight_code": "Lb",
        "weight_name": "POUNDS",
        "height_code": "ft",
        "height_name": "FOOT"
        }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}


### Actualizar parametros de ajuste de usuario[PUT]

+ Attributes
    + height_code: `FT` (enum) - Codigo del enumerado de configuracion de peso
        + FT - PIES
        + M - METROS
    + weight_code: `KG` (enum) - Codigo del enumerado de configuracion de altura
        + KG - KILOGRAMO
        + LB - LIBRAS
    + language_code: `EN` (enum) -  codigo del enumerado de configuracion de lenguaje
        + EN - ENGLISH
        + ES - SPANISH

+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  + Body
     {
        "language_code": "EN",
        "language_name": "ENGLISH",
        "weight_code": "Lb",
        "weight_name": "POUNDS",
        "height_code": "ft",
        "height_name": "FOOT"
        }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}




## Biografia [/user/{userId}/biography]

### Obtener Biografia [GET]


+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
        
   
+ Response 200 (application/json)   
 
   + Body
        {
            "configuration": {
                "phone": true,
                "address": true
            },
            "biography": {
                "user_id": 1,
                "disability": "visual",
                "disability_code": "DI002",
                "marital_status": "single",
                "marital_status_code": "MS001",
                "academic_level": "student",
                "academic_level_code": "AL001",
                "gender": "male",
                "gender_code": "GE001",
                "image_profile": "http://35.227.223.87/image120181010154016319.jpg",
                "name": "oscar",
                "last_name": "Montilla",
                "nickname": "omontilla"
                 }
        }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema
  
    + Body
    {"error_code": "M0009","message": "no found userId"}

### Actualizar Biografia [PUT /user/{userId}/biographyForm]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario

+ Request (application/json) 

    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
  
    + Body
    + Attributes
        + gender_code: `GE001` (optional) - Genero de usuario
        + academic_code: `AL001` (optional) - Nivel academico de usuario
        + marital_code: `MS001` (optional) - Estado civil de usuario
        + disability_code: `DI002` (optional) - Discapacidad de usuario
        + about_me: `about` (optional) - Descripcion del usuario 
        + phone: `5519278` (optional) - Telefono de usuario
        + address: `Av. El centro` (optional) - Direccion de usuario
        + nick_name: `omontilla` (optional) - Nick de usuario
        + name: `Oscar` (optional) - Nombre de usuario
        + last_name: `Montilla` (optional) - Apellido de usuario
        
        
+ Response 200 (application/json)   

  + Headers
     Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
            
   + Body
   {"message": "update"}
   
## ComboBox del Sistema [/user/{userId}/comboBox/]
### ComboBox de deportes [GET /user/{userId}/comboBox/SPORT]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
        
+ Response 200 (application/json)   
   + Body
    {
        "sports": [
            {
                "name": "Volleyball",
                "code": "CS001",
                "image_url": "https://www.shareicon.net/data/128x128/2016/12/23/866375_ball_512x512.png"
            },
            {
                "name": "Futbol",
                "code": "CS002",
                "image_url": "https://www.shareicon.net/data/128x128/2016/11/15/852637_team_512x512.png"
            },
            {
                "name": "Tennis",
                "code": "CS004",
                "image_url": "https://www.shareicon.net/data/128x128/2016/11/15/852637_team_512x512.png"
            }
        ]
    }
       
## Deportes de usuario [/user/{userId}/sport]

### Obtener Deportes [GET /user/{userId}/sport] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
        
+ Response 200 (application/json)   
   + Body
       {
        "sports": [
            {
                "sport_id": 2,
                "sport_code": "CS003",
                "image_url": "https://www.shareicon.net/data/128x128/2016/11/15/852643_game_512x512.png",
                "certifications": [],
                "total_items_certifications": 0,
                "careers": [
                    {
                        "career_id": 13,
                        "description": "s,pa",
                        "date_init": "2018-10-18",
                        "title": "poask"
                    },
                    {
                        "career_id": 12,
                        "description": "kasml",
                        "date_init": "2018-10-18",
                        "title": "oisjao"
                    },
                    {
                        "career_id": 11,
                        "description": "kmas",
                        "date_init": "2018-10-18",
                        "title": "oiasjo"
                    },
                    {
                        "career_id": 10,
                        "description": "klasm",
                        "date_init": "2018-10-18",
                        "title": "pokas"
                    },
                    {
                        "career_id": 9,
                        "description": "kamsl",
                        "date_init": "2018-10-18",
                        "title": "kasml"
                    },
                    {
                        "career_id": 8,
                        "description": "ioasi",
                        "date_init": "2018-10-18",
                        "title": "lkasm"
                    },
                    {
                        "career_id": 7,
                        "description": "kmas",
                        "date_init": "2018-10-18",
                        "title": "iuas"
                    },
                    {
                        "career_id": 6,
                        "description": "pokas",
                        "date_init": "2018-10-18",
                        "title": "poask"
                    },
                    {
                        "career_id": 5,
                        "description": "kamsd",
                        "date_init": "2018-10-18",
                        "title": "jkansk"
                    }
                ],
                "total_items_careers": 11,
                "attributes": [],
                "references": [],
                "total_items_references": 0,
                "is_principal": false
            },
            {
                "sport_id": 1,
                "sport_code": "CS005",
                "image_url": "https://www.shareicon.net/data/128x128/2016/11/15/852637_team_512x512.png",
                "certifications": [
                    {
                        "certification_id": 1,
                        "authority": "Juegos internacionales",
                        "date_init": "2018-11-16",
                        "licence_number": "54s55ajnsjs",
                        "title": "balon de oro",
                        "expired": true
                    }
                ],
                "total_items_certifications": 1,
                "careers": [
                    {
                        "career_id": 1,
                        "description": "juegos internacionales 2017",
                        "date_init": "2018-11-16",
                        "title": "Centro campista"
                    }
                ],
                "total_items_careers": 1,
                "attributes": [],
                "references": [],
                "total_items_references": 0,
                "is_principal": false
            }
        ]
}

### Registrar Deporte [POST /user/{userId}/sport]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

   + Body
    {
    "sport_code": "CS001",
    "attributes":  ["Arquero", "Lateral", "volante"],
    "video": "",
    "video_preview":"",
    "careers": 
    [{"description":"juegos internacionales 2017",
    "date_init": "2017-12-14",
    "date_end":"",
    "present":true,
    "title": "Centro campista"}],
    "certificatios":
    [{"authority": "Juegos internacionales","date_end": "",
    "expired": true,
    "date_init": "2018-08-14",
    "licence_number": "54s55ajnsjs",
    "title": "balon de oro"
    }}
    
+ Response 200 (application/json)   

  + Body
  {"id": 3}
 
+ Response 400 (application/json)         
  El deporte ya se encuentra registrado para el usuario.
  
  + Body
  {"error_code": "M0011","message": "The sport (:sport) is already registered"}
    
### Eliminar Deporte [DELETE /user/{userId}/sport/{sportId}]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
### Colocar como principal un deporte [PUT /user/{userId}/sport/{sportId}/principal]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  Se ha actualizado el registro de deporte como principal
+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
  
## Certificaciones de un deporte [/user/1/sport/1/certification]

### Obtener certificaciones [GET /user/{userId}/sport/{sportId}/certification] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    + page = `0` (optional, number, `1`) ... The page to retrieve
    + items = `0` (optional, number, `1`) ... The number of items per page.
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  + Body
  {
    "certifications": [
        {
            "certification_id": 1,
            "authority": "Juegos internacionales",
            "date_init": "2018-11-16",
            "licence_number": "54s55ajnsjs",
            "title": "balon de oro",
            "expired": true
        }
    ],
    "total_items_certifications": 1
  }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
### Registrar certificacion [POST /user/{userId}/sport/{sportId}/certification] 
  
+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    
+ Request (application/json) 
  
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
    
    + Body
    + Attributes
        + title: titulo (required) - titulo de la certificacion
        + authority: `autoridad` (required) - autoridad de la certificacion
        + date_init: `2018-09-14`  (required) - Fecha de inicio de la certificacion
        + licence_number: `123456` (required) - Numero de licencia de la certificacion
        + expired: true (required,boolean) - Si ha expirado o no la certificacion

+ Response 200 (application/json)   
  + Body        
  {
    "certifications": [
        {
            "certification_id": 3,
            "authority": "autización",
            "date_init": "2018-08-14",
            "licence_number": "123456",
            "title": "titulo",
            "expired": false
        },
        {
            "certification_id": 1,
            "authority": "Juegos internacionales",
            "date_init": "2018-11-16",
            "licence_number": "54s55ajnsjs",
            "title": "balon de oro",
            "expired": true
        }
    ],
    "total_items_certifications": 2
}

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
### Actualizar certificacion [PUT /user/{userId}/sport/{sportId}/certification] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    
+ Request (application/json) 
  
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
    
    + Body
    + Attributes
        + certification_id: `1` (required) - Identificador de certificacion
        + title: titulo (optional) - titulo de la certificacion
        + authority: `autoridad` (optional) - autoridad de la certificacion
        + date_init: `2018-09-14`  (optional) - Fecha de inicio de la certificacion
        + licence_number: `123456` (optional) - Numero de licencia de la certificacion
        + expired: true (optional,boolean) - Si ha expirado o no la certificacion
        
+ Response 200 (application/json)   
  + Body
  {
    "certifications": [
        {
            "certification_id": 1,
            "authority": "autizaciónmnnnnnnnnn",
            "date_init": "2018-09-14",
            "licence_number": "123456",
            "title": "dsadsadsadsadsa",
            "expired": true
        }
    ],
    "total_items_certifications": 1
}

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
+ Response 400 (application/json) 
  El identificador de certification_id no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found certification_id"}
  
### Eliminar certificacion [DELETE /user/{userId}/sport/{sportId}/certification/{certificationId}] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    + certificationId: `1` (required,number) - Identificador de certificacion
    
+ Request (application/json) 
  
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  Se elimino la certificacion
  + body  
  
+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
+ Response 400 (application/json) 
  El identificador de certification_id no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found certificationId"}
  

## Carrera de un deporte [/user/1/sport/1/career]

### Obtener Carreras [GET /user/{userId}/sport/{sportId}/career] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    + page = `0` (optional, number, `1`) ... The page to retrieve
    + items = `0` (optional, number, `1`) ... The number of items per page.
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  + Body
    {
    "careers": [
        {
            "career_id": 1,
            "description": "juegos internacionales 2017",
            "date_init": "2018-11-16",
            "present": true,
            "title": "Centro campista"
        }
    ],
    "total_items_careers": 1
    }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
### Registrar carrera [POST /user/{userId}/sport/{sportId}/career] 
  
+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    
+ Request (application/json) 
  
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
    
    + Body
    + Attributes
        + title: titulo (required) - titulo de la carrera
        + description: `description` (required) - Descripcion de la carrera
        + date_init: `2018-09-14`  (required) - Fecha de inicio de la carrera
        + date_end: `` (optional) - Fecha de cierre de la carrera carrera
        + present: true (required,boolean) - Si esta cursando actualmente la carrera

+ Response 200 (application/json)   
  + Body        
  {
    "careers": [
        {
            "career_id": 15,
            "description": "lelelel",
            "date_init": "0031-09-11",
            "present": true,
            "title": "lalala"
        },
        {
            "career_id": 1,
            "description": "juegos internacionales 2017",
            "date_init": "2018-11-16",
            "present": true,
            "title": "Centro campista"
        }
    ],
    "total_items_careers": 2
    }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
### Actualizar carrera [PUT /user/{userId}/sport/{sportId}/career] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    
+ Request (application/json) 
  
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA
    
    + Body
    + Attributes
        + career_id: `1` (required) - Identificador de carrera
        + title: titulo (optional) - titulo de la carrera
        + description: `description` (optional) - descripcion de la carrera
        + date_init: `2018-09-14`  (optional) - Fecha de inicio de la certificacion
        + date_end: `123456` (optional) - Fecha de cierre de la carrera carrera

        
+ Response 200 (application/json)   
  + Body
    {
    "careers": [
        {
            "career_id": 15,
            "description": "csawqdqxq",
            "date_init": "0026-09-11",
            "date_end": "0026-09-11",
            "present": true,
            "title": "dsadsacas"
        },
        {
            "career_id": 1,
            "description": "juegos internacionales 2017",
            "date_init": "2018-11-16",
            "present": true,
            "title": "Centro campista"
        }
    ],
    "total_items_careers": 2
    }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
+ Response 400 (application/json) 
  El identificador de career_id no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found career_id"}
  
### Eliminar carrera [DELETE /user/{userId}/sport/{sportId}/career/{careerId}] 

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + sportId: `1` (required,number) - Identificador de deporte
    + careerId: `1` (required,number) - Identificador de carrera
    
+ Request (application/json) 
  
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  Se elimino la carrera
  + body  
  
+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  El identificador de sportId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sportId"}
  
+ Response 400 (application/json) 
  El identificador de careerId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found careerId"}

## Notificaciones [/user/{userId}/notifications]

### Obtener Notificaciones [GET /user/{userId}/notifications?lat={lat}&lng={lng}]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + page: `0` (optional, string)  - Numero de pagina
    + items: `10` (optional, string) - Cantidad de registros a consultar
    + lat: `19.4284700` (required, string) - Latitud del usuario
    + lng: `99.1276600` (required, string) - Longitud del usuario
    
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 200 (application/json)   
  + Body
    {
    "notifications": [
        {
            "notification_id": 1,
            "code": "MN001",
            "image": "http://35.227.223.87/image120181010154016319.jpg",
            "time": "2018-11-30 13:02:33"
        }
    ],
    "total_items_notifications": 1
    }

+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json) 
  faltan campos obligatorios
  
  + Body
  {"error_code": "M0003","message": "The field is required"}
  
### Enviar Referencia [POST /user/{userId}/notifications/reference/{userIdInvite}]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + userIdInvite: `2` (required,number) - Identificador del usuario al que se envio la referencia
    + page = `0` (optional, number, `1`) - La Cantidad de paginas
    + items = `0` (optional, number, `1`) - Cantidad de items por pagina.
    
        
+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Attributes
    + sport_id: `1` (required,number) - Identificador de deporte del usuario al que se envio la referencia
    + description: `Comentario de la referencia` (required,string) - Nivel academico de usuario
  

+ Response 201 (application/json)
  La referencia se ha enviado 
  + body
    
+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json)         
  Ya has enviado una referencia.

  + Body
  {"error_code": "M0014","message": "You have already sent a reference"}  
  
+ Response 400 (application/json) 
  El identificador de sport_id no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found sport_id"}
  
### Enviar Solicitud de amistad [POST /user/{userId}/notifications/friend/{userIdInvite}]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario
    + userIdInvite: `2` (required,number) - Identificador del usuario al que se envio la referencia
    + page = `0` (optional, number, `1`) - La Cantidad de paginas
    + items = `0` (optional, number, `1`) - Cantidad de items por pagina.

+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA

+ Response 201 (application/json)
  La referencia se ha enviado 
  + body      
  
+ Response 400 (application/json)         
  El identificador de userId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found userId"}
  
+ Response 400 (application/json)         
  Ya has enviado una solicitud de amistad.

  + Body
  {"error_code": "M0013","message": "You have already sent a friend request"}  
  
### Aceptar/declinar solicitudes de amistad o referencia [POST /user/{userId}/notifications/{notificationId}/condition/{condition}]

+ Parameters
    + userId: `1` (required,number) - Identificador de usuario.
    + notificationId: `2` (required,number) - Identificador de notificacion.
    + condition = true (required,boolean, `true`) - Condicion si acepta o declina la notificacion

+ Request (application/json) 
    + Headers
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiZW1haWwiOiJtb250aWxsYS50MzFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoiaW9uaWNfYXBwIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImdyb3VwcyI6IiBzdXBlciIsImlhdCI6MTUzNzI4MDY5OSwic3ViIjoibW9udGlsbGEudDMxQGdtYWlsLmNvbSIsImlzcyI6IlN0YWxmeSJ9.I400_t5y6KEpIY586Tv8QCFDirg72TzZgsVSBPLq76mxLxnJsAE0_MURPXLTr1zxv4y6MJdadFDu5dYvTNu7FA


+ Response 200 (application/json)
  Has aceptado la referencia enviada por (name)
  + body     
    {
    "error_code": "M0017",
    "message": "You have accepted the reference sent by (name)."
    }
    
+ Response 200 (application/json)
  Ahora (name) son y tus amigos.
  + body     
    {
    "error_code": "M0015",
    "message": "Now (name) are and your friends."
    }
    
+ Response 400 (application/json)         
  El identificador de notificationId no existe en el sistema

  + Body
  {"error_code": "M0009","message": "no found notificationId"}